// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDau_mEUihC5l5S6Aa5ipMA7hIrAT243o',
    appId: '1:518527099177:web:8aadc6659aa6c41bd71738',
    messagingSenderId: '518527099177',
    projectId: 'jostic-demo',
    authDomain: 'jostic-demo.firebaseapp.com',
    storageBucket: 'jostic-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQKVVGJo-lfrdyEEuNDFgel3bCU5JbGQ',
    appId: '1:518527099177:android:8d08238e484a6b74d71738',
    messagingSenderId: '518527099177',
    projectId: 'jostic-demo',
    storageBucket: 'jostic-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPondG-pZjCgz-dk05P4_vxEmFk9gaNp4',
    appId: '1:518527099177:ios:c176b555ebda0df0d71738',
    messagingSenderId: '518527099177',
    projectId: 'jostic-demo',
    storageBucket: 'jostic-demo.appspot.com',
    androidClientId: '518527099177-9qqba5uacndo4a2dbe7nnm1upk3h622p.apps.googleusercontent.com',
    iosClientId: '518527099177-mlm0tuk31e243na2cbbu1dpa89t5pije.apps.googleusercontent.com',
    iosBundleId: 'com.example.joisticTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPondG-pZjCgz-dk05P4_vxEmFk9gaNp4',
    appId: '1:518527099177:ios:c176b555ebda0df0d71738',
    messagingSenderId: '518527099177',
    projectId: 'jostic-demo',
    storageBucket: 'jostic-demo.appspot.com',
    androidClientId: '518527099177-9qqba5uacndo4a2dbe7nnm1upk3h622p.apps.googleusercontent.com',
    iosClientId: '518527099177-mlm0tuk31e243na2cbbu1dpa89t5pije.apps.googleusercontent.com',
    iosBundleId: 'com.example.joisticTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDau_mEUihC5l5S6Aa5ipMA7hIrAT243o',
    appId: '1:518527099177:web:f50219f214ef4d5ed71738',
    messagingSenderId: '518527099177',
    projectId: 'jostic-demo',
    authDomain: 'jostic-demo.firebaseapp.com',
    storageBucket: 'jostic-demo.appspot.com',
  );
}
